<TestLog><TestSuite name="TestModule"><TestSuite name="TestSuite1"><TestCase name="SucceddedCheckTest"><TestingTime>344</TestingTime></TestCase><TestCase name="ExceptionTest"><Exception file="unknown location" line="0"><![CDATA[std::runtime_error: error]]></Exception><TestingTime>659</TestingTime></TestCase><TestCase name="FailedCheckTest"><Error file="btest_linux.cpp" line="23"><![CDATA[check 1 == 0 failed [1 != 0]]]></Error><Error file="btest_linux.cpp" line="24"><![CDATA[check 1 == 2 failed [1 != 2]]]></Error><TestingTime>370</TestingTime></TestCase><TestCase name="FailedRequireCheckTest"><Error file="btest_linux.cpp" line="29"><![CDATA[check 1 == 0 failed [1 != 0]]]></Error><FatalError file="btest_linux.cpp" line="30"><![CDATA[critical check 1 == 0 failed]]></FatalError><TestingTime>332</TestingTime></TestCase><TestCase name="SucceddedWarnTest"><Warning file="btest_linux.cpp" line="35"><![CDATA[condition 1 == 0 is not satisfied [1 != 0]]]></Warning><Warning file="btest_linux.cpp" line="36"><![CDATA[condition 1 == 2 is not satisfied [1 != 2]]]></Warning><Message file="./boost/test/impl/results_collector.ipp" line="220"><![CDATA[Test case SucceddedWarnTest did not check any assertions]]></Message><TestingTime>408</TestingTime></TestCase><TestCase name="SucceddedMessageTest"><Message file="btest_linux.cpp" line="41"><![CDATA[blablabla]]></Message><Message file="btest_linux.cpp" line="42"><![CDATA[abba]]></Message><TestingTime>302</TestingTime></TestCase><TestCase name="EmptyTest"><Message file="./boost/test/impl/results_collector.ipp" line="220"><![CDATA[Test case EmptyTest did not check any assertions]]></Message><TestingTime>162</TestingTime></TestCase><TestCase name="CheckpointTest"><Exception file="unknown location" line="0"><![CDATA[std::runtime_error: error]]><LastCheckpoint file="btest_linux.cpp" line="52"><![CDATA[This is a checkpoint]]></LastCheckpoint></Exception><TestingTime>172</TestingTime></TestCase><TestCase name="OneSecSuccededTest"><TestingTime>197</TestingTime></TestCase></TestSuite><TestSuite name="TestSuite2"><TestSuite name="NestedTestSuite1"><TestSuite name="NestedTestSuite2"><TestCase name="NestedTest"><Error file="btest_linux.cpp" line="71"><![CDATA[check false == true failed]]></Error><TestingTime>392</TestingTime></TestCase></TestSuite></TestSuite></TestSuite></TestSuite></TestLog>